# mostly from: https://caddyserver.com/docs/running#docker-compose

# To start: docker compose up -d
# to reload with new Caddyfile: docker compose exec -w /etc/caddy caddy caddy reload
# to see recent logs: docker compose logs caddy -n=100 -f
# to format Caddyfile: docker compose exec -w /etc/caddy caddy caddy fmt --overwrite
services:
  caddy:
    image: caddy:2.10.0-alpine
    restart: unless-stopped # restart automatically if in case machine is rebooted
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp" # used for HTTP/3
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile # mount Caddyfile to container
      # - ./site:/srv # mount site folder to container --> used for statically serving files if configured
      - caddy_data:/data # contains things like TLS certificates https://caddyserver.com/docs/conventions#file-locations
      - caddy_config:/config # stores confiugrations, e.g. the latest active caddyfile https://caddyserver.com/docs/conventions#file-locations
    extra_hosts:
      - "host.docker.internal:host-gateway" # allows the container to access the host machine (also on linux) https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach/24326540#24326540
      
volumes:
  caddy_data:
  caddy_config:
